### ISSUE TITLE
extraneous folder

### ISSUE THREAD

**Issue by kristopolous** [kristopolous/mansnip#3]
https://www.reddit.com/r/commandline/comments/g5nhgj/mansnip_a_better_way_to_search_manpages/fo5c7o6/
> the Pip installer just made a folder that doesn't seem to contain the main mansnip Python file. No intention to make this into a tech support thread, just thought I'd point it out. :-)

**Comment by kristopolous** [comment]
so I can't replicate this.
I reached out to the reddit user for clarification

**Comment by EagTG** [comment]
Hi Kristopolous,

I was running Ubuntu 19.10, and didn't have PIP3 installed, so I did:
sudo apt install python3-pip

Then ran the following command:
pip3 install mansnip-kristopolous

I couldn't find where it installed, so after some searching...
pip3 show mansnip-kristopolous

This told me it was in...
cd ~/.local/lib/python3.7/site-packages/mansnip_kristopolous-0.3.2.dist-info/

The contents of that folder didn't seem to have the primary binary/Python script:
INSTALLER
LICENSE
METADATA
RECORD
top_level.txt
WHEEL

Is this just as simple as me not looking in the right place for where PIP is installing?

To reiterate information shared in the Reddit post, installing manually from the GitHub repo has resolved the issue for my use of Mansnip. Happy to continue troubleshooting here to assist in the debugging process (if necessary).

Thanks again!
-Todd

**Comment by kristopolous** [comment]
It puts the executable script in `~/.local/bin` as per the usual python-pip convention. The executable should be there in `~/.local/bin`. Feel free to check

**Comment by EagTG** [comment]
It is. Disregard this bug, just my unfamiliarity with PIP. Adding that to my path now. :-)
