### ISSUE TITLE
Random results

### ISSUE THREAD

**Issue by AtomToast** [kristopolous/mansnip#5]
I am seemingly getting random results everytime I execute the script:  

![](https://i.imgur.com/oGUQp06.png)

System is Arch Linux, running zsh

**Comment by kristopolous** [comment]
That's based on your window size. Man reflows based on the width. The line number isn't a constant, it's actually dynamic.

**Comment by kristopolous** [comment]
So it's technically "not a bug" I mean I know it's not obvious but I don't think I should change this existing behavior of man. Re-open if you feel otherwise!

**Comment by kristopolous** [comment]
wait I understand your use case ... you have two windows side by side, one is a reference, the other is a viewer, right? Yes, this thing will go nuts with that approach. I agree.  It's a totally valid concept of a workflow. We're trying to make things easier here. I'll think about how to pull that off.
