### ISSUE TITLE
No result in most cases

### ISSUE THREAD

**Issue by SmartFinn** [kristopolous/mansnip#7]
Hello.

I like the idea of this utility, but in most cases it does not return a result, even for the examples in README.

```
$ > ./mansnip tar -x -z -v -f
$ > ./mansnip tar -x
$ > ./mansnip ping -w
$ > ./mansnip ping -c
$ > ./mansnip bash -e
$ > ./mansnip bash -z
$ > ./mansnip find -printf
547  EXPRESSION
     ACTIONS
       -printf format
...
787  UNUSUAL FILENAMES
       -printf, -fprintf
...
$ > ./mansnip journalctl -x
$ > ./mansnip awk -f
$ > ./mansnip sed -i
$ > ./mansnip grep -E
$ > 
```

All of these queries request valid manpages and options.

**Disto:** Fedora 32
**Python version:** 3.8 (with 3.7 the same)
**Mansnip version:** master branch

**Comment by kristopolous** [comment]
thanks i just saw this ... let me look

**Comment by kristopolous** [comment]
these all except for awk works for me. could you give me ssh access if you're still interested?

**Comment by SmartFinn** [comment]
> could you give me ssh access if you're still interested?

It's hard to do because my machine behind NAT but you can get the same environment with `docker`/`podman` with the command:

```sh
docker run --rm -ti registry.fedoraproject.org/f33/fedora-toolbox:33 bash
[root@a6ae691285d9 /]# pip install mansnip-kristopolous
[root@a6ae691285d9 /]# mansnip tar -x
[root@a6ae691285d9 /]# mansnip ping -c
[root@a6ae691285d9 /]# mansnip awk -f
[root@a6ae691285d9 /]# mansnip mansnip sed -i
```

**Comment by kristopolous** [comment]
wonderful. That's a great starting point. The actual manpage pipeline is pretty crazy so I'll look into this, I'm probably hooking in a way that's not universal. Thanks a lot! I really appreciate it.

**Comment by kristopolous** [comment]
oh they brought back the auto-closer .... fuck that feature

**Comment by kristopolous** [comment]
i hate how github imposes a workflow. anyway that commit should fix it. feel free to confirm.

**Comment by SmartFinn** [comment]
Now it works wonderfully. Thank you :+1:
